// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto
#define PROTOBUF_USE_DLLS

#ifndef GOOGLE_PROTOBUF_INCLUDED_data_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_data_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_data_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_data_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_data_2eproto;
namespace customstream {
class FrameData;
struct FrameDataDefaultTypeInternal;
extern FrameDataDefaultTypeInternal _FrameData_default_instance_;
class FrameDataList;
struct FrameDataListDefaultTypeInternal;
extern FrameDataListDefaultTypeInternal _FrameDataList_default_instance_;
}  // namespace customstream
PROTOBUF_NAMESPACE_OPEN
template<> ::customstream::FrameData* Arena::CreateMaybeMessage<::customstream::FrameData>(Arena*);
template<> ::customstream::FrameDataList* Arena::CreateMaybeMessage<::customstream::FrameDataList>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace customstream {

// ===================================================================

class FrameData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:customstream.FrameData) */ {
 public:
  inline FrameData() : FrameData(nullptr) {}
  ~FrameData() override;
  explicit PROTOBUF_CONSTEXPR FrameData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FrameData(const FrameData& from);
  FrameData(FrameData&& from) noexcept
    : FrameData() {
    *this = ::std::move(from);
  }

  inline FrameData& operator=(const FrameData& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameData& operator=(FrameData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FrameData& default_instance() {
    return *internal_default_instance();
  }
  static inline const FrameData* internal_default_instance() {
    return reinterpret_cast<const FrameData*>(
               &_FrameData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FrameData& a, FrameData& b) {
    a.Swap(&b);
  }
  inline void Swap(FrameData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FrameData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FrameData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FrameData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FrameData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FrameData& from) {
    FrameData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FrameData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "customstream.FrameData";
  }
  protected:
  explicit FrameData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kMessageFieldNumber = 9,
    kFrameFieldNumber = 2,
    kPtsFieldNumber = 3,
    kTimeMsFieldNumber = 4,
    kDataIdFieldNumber = 5,
    kValueFieldNumber = 6,
    kSpeedFieldNumber = 7,
    kTemperatureFieldNumber = 8,
    kLongitudeFieldNumber = 10,
    kLatitudeFieldNumber = 11,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string message = 9;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // int64 frame = 2;
  void clear_frame();
  int64_t frame() const;
  void set_frame(int64_t value);
  private:
  int64_t _internal_frame() const;
  void _internal_set_frame(int64_t value);
  public:

  // int64 pts = 3;
  void clear_pts();
  int64_t pts() const;
  void set_pts(int64_t value);
  private:
  int64_t _internal_pts() const;
  void _internal_set_pts(int64_t value);
  public:

  // int64 time_ms = 4;
  void clear_time_ms();
  int64_t time_ms() const;
  void set_time_ms(int64_t value);
  private:
  int64_t _internal_time_ms() const;
  void _internal_set_time_ms(int64_t value);
  public:

  // int64 data_id = 5;
  void clear_data_id();
  int64_t data_id() const;
  void set_data_id(int64_t value);
  private:
  int64_t _internal_data_id() const;
  void _internal_set_data_id(int64_t value);
  public:

  // int64 value = 6;
  void clear_value();
  int64_t value() const;
  void set_value(int64_t value);
  private:
  int64_t _internal_value() const;
  void _internal_set_value(int64_t value);
  public:

  // double speed = 7;
  void clear_speed();
  double speed() const;
  void set_speed(double value);
  private:
  double _internal_speed() const;
  void _internal_set_speed(double value);
  public:

  // double temperature = 8;
  void clear_temperature();
  double temperature() const;
  void set_temperature(double value);
  private:
  double _internal_temperature() const;
  void _internal_set_temperature(double value);
  public:

  // double longitude = 10;
  void clear_longitude();
  double longitude() const;
  void set_longitude(double value);
  private:
  double _internal_longitude() const;
  void _internal_set_longitude(double value);
  public:

  // double latitude = 11;
  void clear_latitude();
  double latitude() const;
  void set_latitude(double value);
  private:
  double _internal_latitude() const;
  void _internal_set_latitude(double value);
  public:

  // @@protoc_insertion_point(class_scope:customstream.FrameData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    int64_t frame_;
    int64_t pts_;
    int64_t time_ms_;
    int64_t data_id_;
    int64_t value_;
    double speed_;
    double temperature_;
    double longitude_;
    double latitude_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_data_2eproto;
};
// -------------------------------------------------------------------

class FrameDataList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:customstream.FrameDataList) */ {
 public:
  inline FrameDataList() : FrameDataList(nullptr) {}
  ~FrameDataList() override;
  explicit PROTOBUF_CONSTEXPR FrameDataList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FrameDataList(const FrameDataList& from);
  FrameDataList(FrameDataList&& from) noexcept
    : FrameDataList() {
    *this = ::std::move(from);
  }

  inline FrameDataList& operator=(const FrameDataList& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameDataList& operator=(FrameDataList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FrameDataList& default_instance() {
    return *internal_default_instance();
  }
  static inline const FrameDataList* internal_default_instance() {
    return reinterpret_cast<const FrameDataList*>(
               &_FrameDataList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FrameDataList& a, FrameDataList& b) {
    a.Swap(&b);
  }
  inline void Swap(FrameDataList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FrameDataList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FrameDataList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FrameDataList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FrameDataList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FrameDataList& from) {
    FrameDataList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FrameDataList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "customstream.FrameDataList";
  }
  protected:
  explicit FrameDataList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemsFieldNumber = 1,
  };
  // repeated .customstream.FrameData items = 1;
  int items_size() const;
  private:
  int _internal_items_size() const;
  public:
  void clear_items();
  ::customstream::FrameData* mutable_items(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::customstream::FrameData >*
      mutable_items();
  private:
  const ::customstream::FrameData& _internal_items(int index) const;
  ::customstream::FrameData* _internal_add_items();
  public:
  const ::customstream::FrameData& items(int index) const;
  ::customstream::FrameData* add_items();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::customstream::FrameData >&
      items() const;

  // @@protoc_insertion_point(class_scope:customstream.FrameDataList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::customstream::FrameData > items_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_data_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FrameData

// string name = 1;
inline void FrameData::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& FrameData::name() const {
  // @@protoc_insertion_point(field_get:customstream.FrameData.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FrameData::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:customstream.FrameData.name)
}
inline std::string* FrameData::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:customstream.FrameData.name)
  return _s;
}
inline const std::string& FrameData::_internal_name() const {
  return _impl_.name_.Get();
}
inline void FrameData::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* FrameData::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* FrameData::release_name() {
  // @@protoc_insertion_point(field_release:customstream.FrameData.name)
  return _impl_.name_.Release();
}
inline void FrameData::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:customstream.FrameData.name)
}

// int64 frame = 2;
inline void FrameData::clear_frame() {
  _impl_.frame_ = int64_t{0};
}
inline int64_t FrameData::_internal_frame() const {
  return _impl_.frame_;
}
inline int64_t FrameData::frame() const {
  // @@protoc_insertion_point(field_get:customstream.FrameData.frame)
  return _internal_frame();
}
inline void FrameData::_internal_set_frame(int64_t value) {
  
  _impl_.frame_ = value;
}
inline void FrameData::set_frame(int64_t value) {
  _internal_set_frame(value);
  // @@protoc_insertion_point(field_set:customstream.FrameData.frame)
}

// int64 pts = 3;
inline void FrameData::clear_pts() {
  _impl_.pts_ = int64_t{0};
}
inline int64_t FrameData::_internal_pts() const {
  return _impl_.pts_;
}
inline int64_t FrameData::pts() const {
  // @@protoc_insertion_point(field_get:customstream.FrameData.pts)
  return _internal_pts();
}
inline void FrameData::_internal_set_pts(int64_t value) {
  
  _impl_.pts_ = value;
}
inline void FrameData::set_pts(int64_t value) {
  _internal_set_pts(value);
  // @@protoc_insertion_point(field_set:customstream.FrameData.pts)
}

// int64 time_ms = 4;
inline void FrameData::clear_time_ms() {
  _impl_.time_ms_ = int64_t{0};
}
inline int64_t FrameData::_internal_time_ms() const {
  return _impl_.time_ms_;
}
inline int64_t FrameData::time_ms() const {
  // @@protoc_insertion_point(field_get:customstream.FrameData.time_ms)
  return _internal_time_ms();
}
inline void FrameData::_internal_set_time_ms(int64_t value) {
  
  _impl_.time_ms_ = value;
}
inline void FrameData::set_time_ms(int64_t value) {
  _internal_set_time_ms(value);
  // @@protoc_insertion_point(field_set:customstream.FrameData.time_ms)
}

// int64 data_id = 5;
inline void FrameData::clear_data_id() {
  _impl_.data_id_ = int64_t{0};
}
inline int64_t FrameData::_internal_data_id() const {
  return _impl_.data_id_;
}
inline int64_t FrameData::data_id() const {
  // @@protoc_insertion_point(field_get:customstream.FrameData.data_id)
  return _internal_data_id();
}
inline void FrameData::_internal_set_data_id(int64_t value) {
  
  _impl_.data_id_ = value;
}
inline void FrameData::set_data_id(int64_t value) {
  _internal_set_data_id(value);
  // @@protoc_insertion_point(field_set:customstream.FrameData.data_id)
}

// int64 value = 6;
inline void FrameData::clear_value() {
  _impl_.value_ = int64_t{0};
}
inline int64_t FrameData::_internal_value() const {
  return _impl_.value_;
}
inline int64_t FrameData::value() const {
  // @@protoc_insertion_point(field_get:customstream.FrameData.value)
  return _internal_value();
}
inline void FrameData::_internal_set_value(int64_t value) {
  
  _impl_.value_ = value;
}
inline void FrameData::set_value(int64_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:customstream.FrameData.value)
}

// double speed = 7;
inline void FrameData::clear_speed() {
  _impl_.speed_ = 0;
}
inline double FrameData::_internal_speed() const {
  return _impl_.speed_;
}
inline double FrameData::speed() const {
  // @@protoc_insertion_point(field_get:customstream.FrameData.speed)
  return _internal_speed();
}
inline void FrameData::_internal_set_speed(double value) {
  
  _impl_.speed_ = value;
}
inline void FrameData::set_speed(double value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:customstream.FrameData.speed)
}

// double temperature = 8;
inline void FrameData::clear_temperature() {
  _impl_.temperature_ = 0;
}
inline double FrameData::_internal_temperature() const {
  return _impl_.temperature_;
}
inline double FrameData::temperature() const {
  // @@protoc_insertion_point(field_get:customstream.FrameData.temperature)
  return _internal_temperature();
}
inline void FrameData::_internal_set_temperature(double value) {
  
  _impl_.temperature_ = value;
}
inline void FrameData::set_temperature(double value) {
  _internal_set_temperature(value);
  // @@protoc_insertion_point(field_set:customstream.FrameData.temperature)
}

// string message = 9;
inline void FrameData::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& FrameData::message() const {
  // @@protoc_insertion_point(field_get:customstream.FrameData.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FrameData::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:customstream.FrameData.message)
}
inline std::string* FrameData::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:customstream.FrameData.message)
  return _s;
}
inline const std::string& FrameData::_internal_message() const {
  return _impl_.message_.Get();
}
inline void FrameData::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* FrameData::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* FrameData::release_message() {
  // @@protoc_insertion_point(field_release:customstream.FrameData.message)
  return _impl_.message_.Release();
}
inline void FrameData::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:customstream.FrameData.message)
}

// double longitude = 10;
inline void FrameData::clear_longitude() {
  _impl_.longitude_ = 0;
}
inline double FrameData::_internal_longitude() const {
  return _impl_.longitude_;
}
inline double FrameData::longitude() const {
  // @@protoc_insertion_point(field_get:customstream.FrameData.longitude)
  return _internal_longitude();
}
inline void FrameData::_internal_set_longitude(double value) {
  
  _impl_.longitude_ = value;
}
inline void FrameData::set_longitude(double value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:customstream.FrameData.longitude)
}

// double latitude = 11;
inline void FrameData::clear_latitude() {
  _impl_.latitude_ = 0;
}
inline double FrameData::_internal_latitude() const {
  return _impl_.latitude_;
}
inline double FrameData::latitude() const {
  // @@protoc_insertion_point(field_get:customstream.FrameData.latitude)
  return _internal_latitude();
}
inline void FrameData::_internal_set_latitude(double value) {
  
  _impl_.latitude_ = value;
}
inline void FrameData::set_latitude(double value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:customstream.FrameData.latitude)
}

// -------------------------------------------------------------------

// FrameDataList

// repeated .customstream.FrameData items = 1;
inline int FrameDataList::_internal_items_size() const {
  return _impl_.items_.size();
}
inline int FrameDataList::items_size() const {
  return _internal_items_size();
}
inline void FrameDataList::clear_items() {
  _impl_.items_.Clear();
}
inline ::customstream::FrameData* FrameDataList::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:customstream.FrameDataList.items)
  return _impl_.items_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::customstream::FrameData >*
FrameDataList::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:customstream.FrameDataList.items)
  return &_impl_.items_;
}
inline const ::customstream::FrameData& FrameDataList::_internal_items(int index) const {
  return _impl_.items_.Get(index);
}
inline const ::customstream::FrameData& FrameDataList::items(int index) const {
  // @@protoc_insertion_point(field_get:customstream.FrameDataList.items)
  return _internal_items(index);
}
inline ::customstream::FrameData* FrameDataList::_internal_add_items() {
  return _impl_.items_.Add();
}
inline ::customstream::FrameData* FrameDataList::add_items() {
  ::customstream::FrameData* _add = _internal_add_items();
  // @@protoc_insertion_point(field_add:customstream.FrameDataList.items)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::customstream::FrameData >&
FrameDataList::items() const {
  // @@protoc_insertion_point(field_list:customstream.FrameDataList.items)
  return _impl_.items_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace customstream

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_data_2eproto
